version: '3'
services:
  mysql-container:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=onlinestore
    ports:
      - 3308:3306

  online-store-docker-container:
    image: online-store-docker-container
    restart: on-failure
    depends_on:
      - mysql-container

    ports:
    - 8080:8080
    environment:
      - DATABASE_HOST= mysql-container
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin123
      - DATABASE_NAME=institute
      - DATABASE_PORT=3308
    build: .

